### ISSUE TITLE
Turn this repository into a pipeline

### ISSUE THREAD

**Issue by arunasank** [osm-in/flood-map#31]
Currently, this repository works fine as a single stand up application for working with flood tracking in a single city, Chennai, but the instructions for setting it up to work for other cities are non-existent, creating great confusion on how to replicate this for a new city.

## TODO: 
* [ ] Write up documentation for how to set this up for any city, as a first pass.
  * [ ] Base map design is the only part that will need to be done manually.
* [ ] Write up a script that automatically sets up street selection interaction on any city.
